- name: Launch app
  docker_container:
    name: simpleapistudents
    image: skafee/tp-devops-simple-api
    pull: true
    recreate: true
    networks:
      - name: app-network
    env:
        USERNAME: usr
        PASSWORD: pwd
        URL: db:5432
        DB: db 