all:
 vars:
   ansible_user: centos # user of my ansible
   ansible_ssh_private_key_file: /home/skafee/cours/s8/id_rsa #my private key to connect to the remote server
 children:
   prod:
     hosts: antoine.perrono.takima.cloud #server domain name