all:
 vars:
   ansible_user: centos # user of my ansible
   ansible_ssh_private_key_file: /home/skafee/cours/s8/id_rsa #my private key to connect to the remote server

   POSTGRES_DB: "db"
   POSTGRES_USER: "usr"
   POSTGRES_PASSWORD: "pwd"
   POSTGRES_PORT: "5432"
   POSTGRES_HOST: "{{ POSTGRES_DB }}:{{POSTGRES_PORT}}"

 children:
   prod:
     hosts: antoine.perrono.takima.cloud #server domain name