all:
 vars:
   ansible_user: centos # user of my ansible

   POSTGRES_DB: "db"
   POSTGRES_USER: "usr"
   POSTGRES_PASSWORD: "pwd"
   POSTGRES_PORT: "5432"
   POSTGRES_HOST: "{{ POSTGRES_DB }}:{{POSTGRES_PORT}}"

 children:
   prod:
     hosts: antoine.perrono.takima.cloud #server domain name