- name: Launch database
  docker_container:
    name: db
    image: skafee/tp-devops-database
    pull: true
    recreate: true
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - name: app-network
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr 
      POSTGRES_PASSWORD: pwd