- name: Launch databass
  docker_container:
    name: db
    image: skafee/tp-devops-database
    pull: true
    recreate: true
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - name: app-network