name: Deployment

on:
  workflow_run:
    workflows: ["Build and push docker image"]
    types:
      - completed
    branches: 
      - main
      - deployment #keep just main on prod env

jobs:
  Deploy_with_ansible:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: ./tp3/ansible
          key: ${{secrets.SERVER_SSH_PRIVATE_KEY}}
          options: |
            -i inventories/setup.yml
            -u centos
            --verbose